name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *" # 在UTC+8的12点运行
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/LibreSpark/LibreTV.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          # 尝试正常合并，如果失败则允许不相关历史并强制以 upstream 为准
          if ! git merge upstream/main; then
            echo "Normal merge failed, attempting to merge with unrelated histories"
            git merge upstream/main --allow-unrelated-histories
          fi

      - name: Push changes to fork
        run: |
          git push origin main

      - name: Handle sync failure
        if: failure()
        run: |
          echo "Error: Failed to sync with upstream repository."
          echo "Possible reasons: code conflicts, network issues, or permissions."
          echo "Please check logs or sync manually."
          exit 1
    
